version: '3.9'
services:
  app:
    #container_name: phpfpm
    build: ./php/
    #container_name: php-container
    container_name: app
    expose:
      - 9000
    restart: always
    #restart: unless-stopped
    #working_dir: /var/www
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    #command:
    #  - curl "https://static.videcdn.net/env_sergeykozlov" -o /tmp/.env
    volumes:
      # work - ./var/www/html:/var/www/html
      - ./var/www:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    ###env_file: .env
    ##volumes:
      #  - "${APP_HOST_DIR}:/var/www/html:ro"
      #- asset-volume:/var/www/html
     ### - ./:/var/www/html
      #- configs-volume:/var/www/html
#    configs:
#      - source: php.ini
#        target: /usr/local/etc/php/php.ini
      #ports:
      #  - "3030:3030"
      #command: php -S="0.0.0.0:3030" -t="/var/www/html"
      #volumes:
      #  - type: volume
      #    source: mydata
      #    target: /:/
      #    volume:
      #      nocopy: true
      #- type: bind
      #  source: ./static
      #  target: /opt/app/static
    #deploy:
    #    replicas: 1
    #    placement:
    #        constraints:
    #            - node.labels.node_no == 3
  nginx:
    image: nginx:alpine
    #build: ./nginx/
    container_name: nginx-container
    #!working_dir: .
    volumes:
      ##- "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      ##- "./etc/nginx/vide.me-location.conf:/etc/nginx/vide.me-location.conf"
      ##- "./etc/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf"
      #- "./etc/ssl:/etc/ssl"
      #- "./web:/var/www/html"
      #- php:/var/www/html
      #- "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      #      - asset-volume:/var/www/html
      #- ./:/var/www/html
      ###      - ./www/html:/var/www/html
      #- configs-volume:/etc/nginx/
      #- ./etc/nginx/:/etc/nginx/conf.d/
      #- ./etc/nginx:/etc/nginx/conf.d
      #####- ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- ./etc/nginx/vide.me-location.conf:/etc/nginx/conf.d/vide.me-location.conf
      #- ./:/var/www/html
      #- ./var/www/html:/var/www/html
      # work - ./var/www/html:/var/www/html
      - ./var/www:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "3070:80"
      #- "3000:443"
    #   environment:
    #     - NGINX_HOST=${NGINX_HOST}
    #command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
      #    env_file: .env
      #volumes:
      #- "${APP_HOST_DIR}:/var/www/html:ro"
      #- "dbdata:/var/www/html"
      #./:/your_path/
    #- .:/myapp-web-api
    #- asset-volume:/var/www/html
    #    links:
    #      - php
#    depends_on:
#      - php
        #   configs:
        #     - source: default.conf
        #       target: /etc/nginx/conf.d/default.conf
        #uid: "103"
        #gid: "103"
      #mode: 0440
    #     - source: fastcgi-php.conf
    #       target: /etc/nginx/fastcgi-php.conf
    #     - source: vide.me-location.conf
    #       target: /etc/nginx/vide.me-location.conf
    #deploy:
    #    replicas: 1
    #    placement:
    #        constraints:
    #            - node.labels.node_no == 4
    networks:
      - app-network

  composer:
    image: composer/composer
      #networks:
    #  - test_network
    ports:
      - "9001:9000"
    volumes:
      # - "./composer:/var/www/"
      # work- "./composer:/composer"
      #- "./:/"
      #- "./:/var/www/"
     # - asset-volume:/var/www/html
      #- "./:/vendor"
      - ./var/www:/var/www
    container_name: composer
    # workworking_dir: /composer
    #working_dir: /
    working_dir: /var/www
    #command: install
    command: update
#  cron:
#    build: ./cron
#    networks:
#      - app-network
volumes:
  #mydata:
  #dbdata:
  asset-volume:
  configs-volume:

#Docker Networks
networks:
  app-network:
    driver: bridge
#configs:
#  default.conf:
#    file: ./etc/nginx/default.conf
#  #my_other_config:
#  #  external: true
#  fastcgi-php.conf:
#    file: ./etc/nginx/fastcgi-php.conf
#  vide.me-location.conf:
#    file: ./etc/nginx/vide.me-location.conf
#  php.ini:
#    file: ./etc/php/php.ini
